-- PAGINE
INSERT INTO pagine VALUES(1, "STORIA APPLE");
INSERT INTO pagine VALUES(2, "");
INSERT INTO pagine VALUES(3, "PRODOTTI APPLE");
INSERT INTO pagine VALUES(4, "STEVE JOBS");

-- TITOLI
INSERT INTO titoli VALUES(1, 1, "FONDAZIONE APPLE", "APPLE'S FOUNDATION");
INSERT INTO titoli VALUES(2, 1, "DIVERGENZE TRA JOBS E SCULLY", "DISAGREEMENTS BETWEEN JOBS AND SCULLEY");
INSERT INTO titoli VALUES(3, 1, "DIFFUSIONE DELL’INTERFACCIA GRAFICA", "SPREAD OF THE GRAPHICAL USER INTERFACE");
INSERT INTO titoli VALUES(4, 1, "CAUSE LEGALI CON MICROSOFT", "LAWSUITS WITH MICROSOFT");
INSERT INTO titoli VALUES(5, 1, "DIMISSIONI DI JOBS E LA FONDAZIONE DI NEXT", "JOBS' RESIGNATION AND THE MERGER OF NEXT");
INSERT INTO titoli VALUES(6, 1, "SCOMPARSA DI STEVE JOBS E FUTURO DELL'AZIENDA", "STEVE JOBS' PASSING AND THE FUTURE OF THE COMPANY");
INSERT INTO titoli VALUES(7, 1, "CAUSA LEGALE CON SAMSUNG", "LAWSUIT WITH SAMSUNG");
INSERT INTO titoli VALUES(8, 1, "LE NUOVE ASSUNZIONI DI APPLE", "NEW HIRES AT APPLE");
INSERT INTO titoli VALUES(9, 1, "ESPANSIONE NEL SETTORE MUSICALE", "EXPANSION IN THE MUSIC BUSINESS");
INSERT INTO titoli VALUES(10, 1, "LA CREAZIONE DI CLIPS E L'ACQUISIZIONE DI SHAZAM", "THE CREATION OF CLIPS AND THE ACQUISITION OF SHAZAM");
INSERT INTO titoli VALUES(11, 1, "NUOVI ACQUISTI", "NEW PURCHASES");

-- PARAGRAFI
INSERT INTO paragrafi VALUES(1, 1, "Stephen Gary Wozniak è nato l’11 agosto 1950 a Sunnyvale. È il fondatore di Apple insieme a Steve Jobs ed è considerato uno dei padri del personal computer. Grazie alle sue competenze informatiche realizzò i primi computer della Apple Computer. Il 1º Aprile 1976 Steve Jobs e Steve Wozniak fondarono Apple Computer,  prendendo come socio di minoranza il più anziano Ronald Wayne che ha già esperienza in campo imprenditoriale.La prima sede della nuova società si pensava essere il garage dei genitori di Jobs, nonostante pero’ successivamente Steve Wozniak in un’intervista dichiaro’ che la sede non fu fondata inizialmente in un garage besi’ in un cubicolo nella sede di HP a Cupertino.Il primo grosso ordine che l’azienda ricevette fu da parte del negozio Byte Shop che chiese 50 Apple I.", "Stephen Gary Wozniak was born on August 11, 1950, in Sunnyvale. He is the founder of Apple along with Steve Jobs and is considered one of the fathers of the personal computer. Thanks to his computer skills he made the first computers of Apple Computer. On April 1, 1976, Steve Jobs and Steve Wozniak founded Apple Computer, taking as a minority partner the older Ronald Wayne who already has experience in business. The first headquarters of the new company was thought to be Jobs' parents' garage, although later Steve Wozniak stated in an interview that the headquarters was not initially founded in a garage but in a cubicle in HP's Cupertino headquarters. The first big order the company received was from the Byte Shop, which asked for 50 Apple I's.");
INSERT INTO paragrafi VALUES(2, 2, "Jobs incolpò per l'insuccesso dell'azienda John Sculley, l'amministratore delegato, chiamato alla Apple l'anno prima da lui stesso. Jobs e Sculley vennero allo scontro, ciascuno attribuendo all'altro la responsabilità del mancato successo.A fronte dell'accaduto i poteri di Jobs furono notevolmente ridotti. Considerando di 'non avere niente da fare', Jobs intraprese alcuni viaggi in Europa e Unione Sovietica per promuovere i computer Apple. In settembre comunicò al consiglio le proprie dimissioni irrevocabili.", "Jobs blamed the company's failure on John Sculley, the CEO, who had been called to Apple the year before by himself. Jobs and Sculley came to clash, each blaming the other for the lack of success. In the face of the incident, Jobs' powers were greatly reduced. Considering he 'had nothing to do,' Jobs undertook several trips to Europe and the Soviet Union to promote Apple computers. In September he informed the board of his irrevocable resignation.");
INSERT INTO paragrafi VALUES(3, 3, "Nel 1985 vi fu una visita di Bill Gates durante la quale Steve Jobs gli mostrò un’anteprima dell’interfaccia grafica usata da Apple. Microsoft ottenne la licenza da Apple e presentò Windows, la propria interfaccia per i sistemi prodotti da IBM e per quelli compatibili di altri produttori. Molte aziende però, copiarono il computer dell’IBM con modelli più economici, che purtroppo sottrassero larghe fette di mercato alla Apple.", "In 1985 there was a visit by Bill Gates during which Steve Jobs showed him a preview of the graphical user interface used by Apple. Microsoft obtained a licence from Apple and presented Windows, its own interface for systems produced by IBM and for compatible systems of other manufacturers. Many companies, however, copied IBM's computer with cheaper models, which unfortunately took large market shares away from Apple.");
INSERT INTO paragrafi VALUES(4, 4, "La concessione a Microsoft degli elementi dell'interfaccia grafica dei Mac per quello sviluppo, firmata da John Sculley, era stata all'origine delle cause legali intentate da Apple a Microsoft per il furto dell’aspetto e funzionalità del System 7 (nome che nel 1997 divenne macOS). La vertenza legale fu sciolta solamente nel 1996. Questo portò ai primi problemi tra Jobs e Sculley, che pretendeva una supervisione più severa sui prodotti futuri", "The granting of elements of the Mac's graphical user interface to Microsoft for that development, signed by John Sculley, had been at the origin of the lawsuits Apple had filed against Microsoft for the theft of the appearance and functionality of System 7 (the name that became macOS in 1997). The legal dispute was only settled in 1996. This led to the first problems between Jobs and Sculley, who demanded stricter supervision of future products.");
INSERT INTO paragrafi VALUES(5, 5, "Nel 1985 Jobs cercò di far cacciare Sculley, ma il consiglio d’amministrazione rimosse proprio Jobs dai suoi doveri manageriali. Egli sì licenziò poi per fondare NeXT, azienda che produceva computer e workstation avanzate. I successivi prodotti Apple come il PowerBook e altri fallimenti portarono Apple nel 1997 ad acquisire per 429 milioni di dollari proprio NeXT, riportando di fatto Steve Jobs in azienda. Visto lo scarso successo del primo computer portatile, il Macintosh Portable, ne venne presentato nel 1990 un nuovo modello, il PowerBook la cui serie era formata da due prodotti distinti, il PowerBook 100, realizzato in collaborazione con Sony e i PowerBook 140 e PowerBook 170. PowerBook stabilì lo standard per tutti i futuri portatili Apple.", "In 1985 Jobs tried to get Sculley ousted, but the board of directors removed Jobs from his managerial duties. He then resigned to found NeXT, a company that produced advanced computers and workstations. Subsequent Apple products such as the PowerBook and other failures led Apple in 1997 to acquire NeXT itself for $429 million, effectively bringing Steve Jobs back into the company. Due to the lack of success of the first portable computer, the Macintosh Portable, a new model, the PowerBook, was introduced in 1990. The PowerBook series consisted of two separate products, the PowerBook 100, produced in collaboration with Sony, and the PowerBook 140 and PowerBook 170. PowerBook set the standard for all future Apple laptops.");
INSERT INTO paragrafi VALUES(6, 6, "Steve Jobs si dimise dalla carica di CEO il 24 agosto 2011 a causa della malattia che lo colpiva, morendo il 5 Ottobre dello stesso anno e venendo sostituito dal direttore operativo Tim Cook. Il primo importante annuncio di prodotto da parte di Apple dopo la scomparsa del fondatore avvenne il 19 gennaio 2012, quando Phil Schiller introdusse iBooks Textbooks per iOS e iBooks Author per Mac OS X a New York. Jobs aveva dichiarato nella sua biografia che voleva reinventare l'industria dei libri di testo e l'educazione.", "Steve Jobs resigned as CEO on 24 August 2011 due to the illness that had struck him, dying on 5 October of the same year, and being replaced by Chief Operating Officer Tim Cook. Apple's first major product announcement since the founder's passing came on 19 January 2012, when Phil Schiller introduced iBooks Textbooks for iOS and iBooks Author for Mac OS X in New York. Jobs had stated in his biography that he wanted to reinvent the textbook industry and education.");
INSERT INTO paragrafi VALUES(7, 7, "Il 20 agosto 2012, in seguito all'aumento del prezzo delle azioni di Apple, aumentò anche la capitalizzazione di mercato dell'azienda a $ 624 miliardi, costituendo un primato mondiale e battendo il record stabilito in precedenza da Microsoft nel 1999. Il 24 agosto 2012, una giuria statunitense stabilì che Samsung dovesse pagare Apple $ 1,05 miliardi di danni in una causa di proprietà intellettuale. Samsung presentò ricorso per il risarcimento dei danni, che la Corte ridusse a $ 450 milioni. La Corte inoltre accolse la richiesta di Samsung di un nuovo processo. Un'e-mail confidenziale scritta da Jobs un anno prima della sua morte viene presentata durante il procedimento del caso Apple contro Samsung Electronics e diviene disponibile al pubblico all'inizio di aprile 2014. L'e-mail viene inviata solo ai 100 dipendenti più anziani dell'azienda e delineava la visione di Jobs del futuro di Apple Inc.", "On 20 August 2012, Apple's share price increase also increased the company's market capitalization to $624 billion, constituting a world record and breaking the record previously set by Microsoft in 1999.  On 24 August 2012, a US jury ruled that Samsung should pay Apple $1.05 billion in damages in an intellectual property lawsuit. Samsung appealed for damages, which the court reduced to $450 million. The Court also granted Samsung's request for a new trial. A confidential e-mail written by Jobs a year before his death is submitted during the proceedings of the Apple v. Samsung Electronics case and becomes publicly available in early April 2014. The e-mail was sent only to the company's 100 most senior employees and outlined Jobs' vision of the future of Apple Inc.");
INSERT INTO paragrafi VALUES(8, 8, "A marzo 2013, Apple deposita un brevetto per un sistema di realtà aumentata in grado di identificare oggetti in un flusso video in diretta e presentare informazioni corrispondenti a questi oggetti attraverso uno strato di informazioni generato dal computer sovrapposto all'immagine del mondo reale.  Il 2 luglio 2013, Apple assume Paul Deneve, presidente belga e AD di Yves Saint Laurent come vicepresidente. Un annuncio di metà ottobre 2013 rivela che l'amministratore delegato di Burberry, Angela Ahrendts, avrebbe intrapreso la carriera di vicepresidente senior di Apple a metà 2014. Ahrendts supervisiona la strategia digitale di Burberry per quasi otto anni e, durante il suo mandato, le vendite aumentano a circa $ 3,2 miliardi e le azioni si triplicano.", "In March 2013, Apple filed a patent for an augmented reality system capable of identifying objects in a live video stream and presenting information corresponding to these objects through a computer-generated information layer superimposed on the real-world image.  On 2 July 2013, Apple hired Paul Deneve, Belgian president and CEO of Yves Saint Laurent, as vice-president. A mid-October 2013 announcement reveals that Burberry's CEO Angela Ahrendts would take up a career as Apple's Senior Vice President in mid-2014. Ahrendts has overseen Burberry's digital strategy for almost eight years and, during her tenure, sales increased to around $3.2 billion, and shares tripled.");
INSERT INTO paragrafi VALUES(9, 9, "Nel primo trimestre del 2014, Apple registra vendite pari a 51 milioni di iPhone e 26 milioni di iPad, stabilendo un nuovo record di vendite trimestrali. Registra un significativo aumento anno su anno delle vendite di Mac. A maggio 2014, la società conferma l'intenzione di acquisire la compagnia audio Beats Electronics da Dr. Dre e Jimmy Iovine, e del servizio di streaming musicale Beats Music per $ 3 miliardi e di vendere i loro prodotti attraverso i punti vendita e i rivenditori Apple. L'acquisizione è stata il più grande acquisto nella storia di Apple.", "In the first quarter of 2014, Apple reported sales of 51 million iPhones and 26 million iPads, setting a new quarterly sales record. It recorded a significant year-on-year increase in Mac sales. In May 2014, the company confirmed its intention to acquire audio company Beats Electronics from Dr. Dre and Jimmy Iovine, and music streaming service Beats Music for $3 billion and to sell their products through Apple shops and retailers. The acquisition was the largest purchase in Apple's history.");
INSERT INTO paragrafi VALUES(10, 10, "A gennaio 2016, un miliardo di dispositivi Apple erano in uso attivo in tutto il mondo.Il 6 aprile 2017, Apple ha lanciato Clips, un'app che consente agli utenti di iPad e iPhone di creare e modificare brevi video con testo, grafica ed effetti, per poterli poi condividere con altri utenti sull'app Messaggi, Instagram, Facebook e altre reti sociali.A giugno 2017, Apple annuncia HomePod, un altoparlante intelligente mirato a competere contro Sonos, Google Home e Amazon Echo. Verso la fine dell'anno, Apple stava acquisendo Shazam, una società specializzata in: musica, TV, film e riconoscimento pubblicitario. L'acquisizione avvenne al costo di $ 400 milioni.", "As of January 2016, one billion Apple devices were in active use worldwide. On 6 April 2017, Apple launched Clips, an app that allows iPad and iPhone users to create and edit short videos with text, graphics and effects, and then share them with other users on the Messages app, Instagram, Facebook and other social networks. In June 2017, Apple announced HomePod, a smart speaker aimed at competing against Sonos, Google Home and Amazon Echo. Towards the end of the year, Apple was acquiring Shazam, a company specialising in music, TV, movies and ad recognition. The acquisition came at a cost of $400 million.");
INSERT INTO paragrafi VALUES(11, 11, "Il 29 gennaio 2019, Apple registra il suo primo calo di ricavi e profitti dall'ultimo decennio. A febbraio 2019 acquista la società di elaborazione conversazionale PullString. Il 25 luglio 2019, Apple e Intel annunciano un accordo per Apple di acquisire il business dei modem per smartphone di Intel Mobile Communications per 1 miliardo di dollari. Il 30 marzo 2020 Apple acquisisce Dark Sky, un'app meteorologica locale. L'app stand alone sarà chiusa alla fine del 2021. Il 3 aprile 2020, Apple acquisisce Voysis, una società con sede a Dublino focalizzata sulla tecnologia artificiale vocale. Il 14 maggio 2020, Apple acquisisce NextVR, una società di realtà virtuale.", "On 29 January 2019, Apple records its first drop in revenues and profits since the last decade. In February 2019, it acquires the conversational computing company PullString. On 25 July 2019, Apple and Intel announce an agreement for Apple to acquire Intel Mobile Communications' smartphone modem business for $1 billion. On 30 March 2020, Apple acquires Dark Sky, a local weather app. The stand-alone app will be shut down at the end of 2021. On 3 April 2020, Apple acquires Voysis, a Dublin-based company focused on voice artificial technology. On 14 May 2020, Apple acquires NextVR, a virtual reality company.");


-- IMMAGINI
INSERT INTO immagini VALUES(1,  1,  "FONDAZIONE1.jpg");
INSERT INTO immagini VALUES(2,  2,  "FONDAZIONE2.png");
INSERT INTO immagini VALUES(3,  3,  "FONDAZIONE3.png");
INSERT INTO immagini VALUES(4,  4,  "FONDAZIONE4.png");
INSERT INTO immagini VALUES(5,  5,  "FONDAZIONE5.png");
INSERT INTO immagini VALUES(6,  6,  "FONDAZIONE6.png");
INSERT INTO immagini VALUES(7,  7,  "FONDAZIONE7.jpg");
INSERT INTO immagini VALUES(8,  8,  "FONDAZIONE8.jpg");
INSERT INTO immagini VALUES(9,  9,  "FONDAZIONE9.png");
INSERT INTO immagini VALUES(10, 10, "FONDAZIONE10.png");
INSERT INTO immagini VALUES(11, 11, "FONDAZIONE11.png");
